### ISSUE TITLE
Missing licenses

### ISSUE THREAD

**Issue by Kjili** [writethedocs/www#109]
I can't seem to find a license for this repository nor the docs on http://www.writethedocs.org/. I started looking for one in the [Beginner's guide](https://www.writethedocs.org/guide/writing/beginners-guide-to-docs/) and dug upwards finally ending up here but still failed to find any license.

Do you have a license for the repository and the docs and if so, which is it?

**Comment by ericholscher** [comment]
Not currently. As per copyright law, all of the content currently here is fully owned by us. We need to make a decision around what we'd want to license it -- my guess is we'll do CC non-commercial .

**Comment by plaindocs** [comment]
Repos now have licences.
