### ISSUE TITLE
Create list of tech writing books

### ISSUE THREAD

**Issue by boltzmann-brain** [writethedocs/www#1157]
Start by copying from these two lists:

- https://gitlab.com/CrispyCB/Write-The-Docs-Reading-List/blob/master/Write%20The%20Docs%20Reading%20List.md
- https://techwritertoolkit.com/resources/reading-list/

**Comment by Preshh0** [comment]
Can I work on this? @boltzmann-brain @plaindocs

**Comment by plaindocs** [comment]
Hi @Preshh0 looks like this might be mostly done in #1158 , but addition to that list are very welcome.
