### ISSUE TITLE
Add display name to sponsor YAML.

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#1170]
So we can easily list sponsors in blog posts / mails outs. We already use `name`  for key, so easier than reconfiguring everything would be adding `display` or `display-name` or something.

- [x] Add entries to Portland 2020 config
- [x] Add to YAML validation
- [x] Update simple sponsor template

CC: @ericholscher @mxsasha I can do this when I've got the talks settled down, or someone else is welcome to pick it up also.

**Comment by ericholscher** [comment]
I added it to the YAML 👍

**Comment by plaindocs** [comment]
@mxsasha do you think this warrants validation?

**Comment by mxsasha** [comment]
Yes, we should validate this. I'll add something for it.

**Comment by mxsasha** [comment]
I added validation in 5f1afd858b17f321a62244c7e17ea40f0730b6b8 - I think that completes this issue?
