### ISSUE TITLE
Leftovers from #1164

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#1172]
Stuff that didn't get done in #1164 

- [x] I've added an Avatar field if exists is a URL we can save to the repo
- [x] I've lazily just used first speaker in the slug, don't know if we should fix that @mxsasha what is the slug logic for multiple speakers )
- [x] Fix sponsor name field #1170 (could probably use validation)
- [ ] [CSS menu issue](https://github.com/writethedocs/www/pull/1164#issuecomment-585319311)
- [x] Add grant date to config
- [x] Show speaker pics

**Comment by plaindocs** [comment]
CC: @mxsasha @ericholscher

**Comment by plaindocs** [comment]
@mxsasha  pretty sure you've fixed almost all of these in that latest PR #1181 right?

**Comment by mxsasha** [comment]
I checked off the ones that we did, not sure what the CSS menu issue is?

**Comment by plaindocs** [comment]
Yeah, doesn't look super important, closing.
