### ISSUE TITLE
Slack invite link is no longer active, can't join Write the docs Slack community 

### ISSUE THREAD

**Issue by ahus1** [writethedocs/www#1252]
On https://www.writethedocs.org/slack/ there is a link to join the slack channel. When I click on the link I receive the message "This link is no longer active".

Please update the link on the page to I can join.

Thanks!

**Comment by plaindocs** [comment]
Hi @ahus1 

I've updated it in https://github.com/writethedocs/www/commit/98058f5160484a874e44b969172552ba3a90b1a4 so you should be able to join now. 

Welcome!
