### ISSUE TITLE
Bad titles

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#130]
Lots of "Permalink to this headline" nonsense.

**Comment by thatdocslady** [comment]
@plaindocs I love it when you don't give context or details ;)

**Comment by plaindocs** [comment]
![permalinktothis](https://cloud.githubusercontent.com/assets/95874/23458973/f959fce0-feb0-11e6-990e-7e147f3c397f.png)

These permalinks feel wrong to me - but maybe this how kids do things these days? 

I planned on fixing the issue myself - hence no details.

**Comment by thatdocslady** [comment]
I have no idea what those mean, and who are those kids you speak of ;)
Recommend to self-assign issues that you don't want me to nag you about <3

**Comment by plaindocs** [comment]
The title for the permalink for each heading in the new WTD template is "Permalink to this headline".

Which feels wrong to me. But I'm hardly an expert.

**Comment by thatdocslady** [comment]
wait now I'm confused, why did you assign to me if you were planning to handle this?

**Comment by ericholscher** [comment]
Believe that's a Sphinx default. Not sure if it's configurable.

**Comment by plaindocs** [comment]
Ah, thanks for that Eric. Closing then. Not really important in the scale of things anyway - I just stumbled across it when looking at the CSS for sponsor display.
