### ISSUE TITLE
File name length

### ISSUE THREAD

**Issue by djwfyi** [writethedocs/www#1311]
Two PRs I submittied (#1305  and #1306) had problems with three deleted files.
I suspect this was due to my OS (Linux Mint 18.3) not liking the length of the file names and refusing to download the files from the repo.

I suggest that we work to limit the number of characters in file names. If I recall correctly, Windows has issues with file name lengths > 255 characters. 

And we don't have control over where a contributor stores the files on their local PC, so we should aim for a file name length that accounts for that.

**Comment by djwfyi** [comment]
To clarify: length is the name of the file plus the entire path to the file.

**Comment by plaindocs** [comment]
Yep, we're gonna be generating more files with the videos from Portland, and we'll take a look at it then.

**Comment by plaindocs** [comment]
@mxsasha do I remember correctly that you fixed this in your recent video update?

**Comment by mxsasha** [comment]
No, still need to look at it.
