### ISSUE TITLE
Create a "Exclusive and biased language replacement" reference for technical documentation

### ISSUE THREAD

**Issue by jaredmorgs** [writethedocs/www#1370]
# Background

I think many resources about this topic were captured in a PR to https://www.writethedocs.org/guide/writing/style-guides/#thinking-about-accessibility-and-bias

The problem is that this is not canonical enough.
What I need right now is a list of non-inclusive, biased words found in tech all with suggested replacements that an organization can grep for when auditing their codebases.

# Research

I've scoured the internet the last day trying to find a resource like this, but to my surprise, it doesn't exist.

Folks in the slack thread have offered these additional resources which are also great:

![master-slave-decision-tree](https://user-images.githubusercontent.com/952793/97649752-db874980-1aa3-11eb-91ea-2f154af1e3bb.png)

https://github.com/retextjs/retext-equality/blob/main/rules.md

https://mysqlhighavailability.com/mysql-terminology-updates/

# Goal

As a collective group we fix this problem for everyone by adding such a resource to WTD.

The minimum terminology we should specify as no longer acceptable in a technical document is the combination of:

* Blacklist/Whitelist 
* Master/Slave

The included image shows some excellent decision tree style guidelines for eradicating Master/Slave and Whitelist/Blacklist which could be worthwhile adding into the guide with proper attribution.

Another thing worth considering is not only specifying acceptable alternatives to these terms but some approaches you should take when searching for and replacing them in your products, and their supporting docs.

For (a very terse) example:

1. Identify the terms in your products and work out a plan to remove them.
2. Decide what terms to apply to your product and under what context to apply them (if necessary)
2. Development team removes terms from the product.
3. Update agreed-upon terms in your documentation.

**Comment by plaindocs** [comment]
Interesting!

I suspect this is overkill for most folks, who just want a no questions asked list, even if it ends up less correct.

You wanna generate those from csv using mermaid or something, right? :-p

**Comment by jaredmorgs** [comment]
Actually, Atlassian just dropped https://atlassian.design/content/inclusive-writing/ which is pretty much *exactly* what I was hoping for.

**Comment by plaindocs** [comment]
That is an excellent resource.
