### ISSUE TITLE
Migrate off Travis CI completely / Fix CI

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#1417]
Dropping a mish mash of thoughts of varying success here.

* One PR where I attempt to clean up the tox config so we only run the spinx build once, and use the output to run the other checks (the yaml lint is pre build) so the sphinx build, vale, and the link checks. That one mostly works. https://github.com/writethedocs/www/pull/1385/

* Another where I look at running our tox config in Github actions. I'm finding it super hard to figure out the intersections of tox + actions, even getting it working with Travis CI was a PITA. https://github.com/writethedocs/www/pull/1386

   The problem with using tox for everything is that you end up running ruby stuff in tox, which it isn't really designed for. And the easiest way to implement official actions (like the two below) is outside of tox. So I couldn't quite figure out the interaction of tox, actions, dependencies.

So, *probably* the right thing to do is split `vale` and `htmlproofer` out of the tox entirely, and use the dedicated actions

* https://github.com/errata-ai/vale-action
* https://github.com/marketplace/actions/htmlproofer

And I think to do that we still need to upload and download artifacts, because htmlproofer works on the output not the input. 

I might be simultaneously overthinking and trying to do much in the one change. Thoughtss @mxsasha @ericholscher

**Comment by mxsasha** [comment]
So, from what I see our workflow is basically to build the docs, and run a series of checks, some on the input, some on the output? We don't really need tox then, right? We could just run them as sequential tasks within one build? As in, we might not need tox? That does give slightly less info on build failure, you'd need to read the logs. But it might simplify the setup a lot, as you retain all the Sphinx build output within the same build. I do this in most of my CI setups.

**Comment by plaindocs** [comment]
Yeah, that was my initial plan. 

Eric wasn't keen. I think we use tox on RTD, and for local testing.

**Comment by mxsasha** [comment]
Other than that, I think the two PRs make sense, and the idea of splitting out htmlproofer and vale. Looks like GitHub should support artifacts like that. But I've only used GH actions once, and that was for a very simple project, so I don't entirely know beyond just hacking at it until it works. That's generally how I build CI setups :)

Not saying we should do this now, but I do have some more complex builds on CircleCI, and they do have a free option for open source projects. If we run into walls with GitHub actions, we can consider that as an alternate.

**Comment by plaindocs** [comment]
Yeah, I'll iterate a little and see how I get on.

**Comment by ericholscher** [comment]
We don't use tox on RTD at all. If it's easier to remove it, we can consider it, but I didn't really see a reason to, and it makes local testing way more complex.

**Comment by jjafuller** [comment]
Looking through this build tooling it looks like it requires contributors to be running several tech stacks locally. Have y'all considered using a cross platform stand alone task runner like https://taskfile.dev instead of tox and building in a docker container instead of natively? This might simplify your migration to GitHub Actions as well.

**Comment by mxsasha** [comment]
I don't know how this is for others, but I actually do very limited local testing. I have a local Python virtualenv, build the html docs, see if things look good, then push it into a branch. Sometimes I run the YAML validation if I've been doing a lot on that. All the other checks fail so rarely for me that I just have CI check them for me.
