### ISSUE TITLE
Improve unconf variable handling

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#1419]
Just so we we don't lose this https://github.com/writethedocs/www/commit/eb864a4993953e1c9155e610240a3a535307afda#commitcomment-46286045 

* I created the Flag because that is how we handle the others. Probably a better way would be to just spin up blank docs when we clone the site, (with a checklist) and use the URL variable directly.
* do we have a way to apply checks only to certain confs / years?  @mxsasha

**Comment by mxsasha** [comment]
Yes, I agree that just looking whether the URL is set, is a better choice where possible (and particularly for new things). It's how the grants work as well, and it just means fewer places to configure, which can go out of sync.

We do not have a way to run certain checks on certain years, so the YAML requirements are pretty flexible. If it starts to bother us, we could start using two templates. Or just stop running the YAML validator for ancient conferences.

**Comment by mxsasha** [comment]
I'm pretty sure we already fixed this.
