### ISSUE TITLE
Add Slackbot info

### ISSUE THREAD

**Issue by djwfyi** [writethedocs/www#1423]
Janine has created several Slackbot autoresponders.
Add those to the /Slack page for future reference.

(Copied from a #meta thread in Slack where she listed them out.)

# ?invite / ?join

Custom response
Slackbot  15 minutes ago
Hi! Want to invite a friend to the Write the Docs Slack? (How kind of you!) They can sign up at this link: https://join.slack.com/t/writethedocs/shared_invite/zt-lqlaz4w6-WCnSTVD25MebjiqowO8EvQ

# ?conferences / ?conference

Custom response
Slackbot  15 minutes ago
Hi! Want information on upcoming and past Write the Docs conferences? We've got a page for that: https://www.writethedocs.org/conf/ And don't forget to check out #wtd-conferences and #meetups!

# ?jobseeking / ?hiring / ?interview / ?interviewing

Custom response
Slackbot  15 minutes ago
Hi! Are you looking to get hired or to hire a documentarian? We have some helpful tips on the Write the Docs website, including interview tips and key skills: https://www.writethedocs.org/hiring-guide/ You may also find #job-posts-only, #work-wanted, #career-advice, and #managing-writers helpful. Good luck!

# ?getstarted / ?resources / ?learn

Custom response
Slackbot  14 minutes ago
Hi! Are you looking for some resources to learn the basics of writing documentation? We've got a collection on the Write the Docs website: https://www.writethedocs.org/about/learning-resources/ And feel free to ask questions in #learn-tech-writing!

# ?coc

Custom response
Slackbot  14 minutes ago
Hi! Are you looking for Write the Docs' Code of Conduct? Look no further: https://www.writethedocs.org/code-of-conduct/ If you have any concerns, please feel free to make a post in #meta or message one of our moderators (@janine, @jrondeau, @ddbeck, @mikejang, @ericholscher, or @plaindocs) directly.

# ?mods / ?moderators / ?modsquad

Custom response
Slackbot  14 minutes ago
Hi! It looks like you're looking for a Slack moderator (https://www.writethedocs.org/team/#moderation-team). You can make a post in #meta, or ping @janine, @jrondeau, @ddbeck, @mikejang, @ericholscher, or @plaindocs privately with your concerns. We'll do everything we can to help you out. Thanks!

**Comment by plaindocs** [comment]
Sounds good. Don't suppose you want to PR directly? https://github.com/writethedocs/www/blob/master/docs/slack.rst ;-)

**Comment by djwfyi** [comment]
I imagine Janine or I one will get to it soon. 
I just didn't want it to get lost or roll out of Slack before one of us had the time. This seemed the best place to hold onto it until it can get done.

**Comment by plaindocs** [comment]
Sure thing! Thanks for dropping them here, and no pressure.
