### ISSUE TITLE
Link to opencomparison return 404

### ISSUE THREAD

**Issue by fcrbe** [writethedocs/www#1438]
Open Comparison mentioned as an example for "Information for people who want to contribute back" (https://github.com/writethedocs/www/blob/master/docs/guide/writing/beginners-guide-to-docs.rst).

Link returns a 404 (https://opencomparison.readthedocs.io/en/latest/contributing.html). If someone got another example, might be interesting to share it.

**Comment by plaindocs** [comment]
Might be this? https://packaginator.readthedocs.io/en/latest/

**Comment by fcrbe** [comment]
Assume it would indeed be https://packaginator.readthedocs.io/en/latest/contributing.html (not sure if it applies to the reasons why it was chosen as an example, but guess it would still be valid as a reference).
