### ISSUE TITLE
Broken Release Notes link on /docs/guide/writing/style-guides.md

### ISSUE THREAD

**Issue by AnneKohler** [writethedocs/www#1503]
In the Release Notes section of the Write the Docs Style Guide, there is a link for Slack that says "more about their release note style". 

This link goes to an error page from Slack. I am unable to find a comparable page, so this link should probably just be removed.

**Comment by barriebyron** [comment]
thank you fixed! https://github.com/writethedocs/www/pull/1501/commits/2d4e92cb95b66c88caeb8d6101c1d047891d7b50#diff-b7c11c911d9fa463a9e5b6b5f0b53bc0fd25b948b7589afbf3c6ee435d48e9b8R146
