### ISSUE TITLE
What should WTD LINT

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#157]
@ericholscher @thatdocslady @Bradamant3 @kelly-o 

I'd like us to agree on a **minimal** list of checks that we should lint in the docs. I'd rather only **break the build** for "meaningful" things, such as insulting language, and only flag more trivial grammar/spelling issues as warnings.

* WTD/RTD branding
* discriminatory language
* thoughts?

Then in the background we can work on fixing up less important errors if we we think that is important. 

Related to #147 and #58

**Comment by ericholscher** [comment]
Agreed for now. Though I think "breaking the build" is the only way to really enforce things. If it's a manual process I have to run, personally I know I won't do it often. However, if it breaks the build I will fix it. I say we move forward with the big things for now, but I do think there's value in adding more checks to "breaking" status over time, as I believe things outside of that status will not be used.

**Comment by plaindocs** [comment]
I tend to agree, with one large BUT.

I'd rather get contributions, and fixup trivial stuff myself than discourage people because they write a doc and get told it has 15 things they need to fix. That balance may shift if we start getting snowed under with PRs...

**Comment by Bradamant3** [comment]
Looks to me as though y'all are fundamentally in agreement: start with the critical handful of must-fixes, see how it goes, and expand iteratively as need arises.

We aren't suffering from a wave of PRs yet, are we?

Back to original issue: slightly paraphrased list:
WTD/RTD branding, yup yup
Discriminatory language: can we flag this one with suggestions for how to fix, at least for cases where one could read it as stupidity or carelessness at work (gendered pronouns, I'm looking at you -- or racial stereotypes, which are often culturally specific)
I'm guessing we'll need to tweak this one if we get global submissions. And it has the potential to be a bit tricky. Definitely needed, will just also need some thoughtful tending.
Does obscenity belong in its own category? Or is it a subset of the previous item?

**Comment by thatdocslady** [comment]
I agree with whatever ya'll agree about. I don't panic if I see 15 things I need to fix in a PR, but maybe someone else will. Going with the herd on this one.
