### ISSUE TITLE
Allow schedule YAML to have duration instead of start time

### ISSUE THREAD

**Issue by mxsasha** [writethedocs/www#1581]
The conference schedule YAML could support a duration instead of start time (except for the first event of the day), to make it easier to edit. This will make the current google sheets schedule obsolete, along with the spreadsheet2schedule script, and make the YAML the single source of truth that is also practical to edit.

Only downside: if you enter the duration in the YAML, you need to build the site to see the calculated start times of every item. If this is very impractical, we can add a script that does the calculation separately and prints the result.

We'd also need a per conference setting of 12h/24h time display.

/cc @plaindocs

**Comment by plaindocs** [comment]
I'd :heart: this! Super into a per-conf 12/24 hour time as well. 
I think YAML as source of truth would work well. 
Script to show the schedule should be super easy if we need it.

**Comment by thatdocslady** [comment]
I'm fine with using the CI to preview the changes in the site, since I don't rely that much on local builds these days

**Comment by plaindocs** [comment]
One other detail, in the past we've started Portland approx 1 hour earlier than Prague? But I guess that is just factored the starting time, so will already be sorted.
