### ISSUE TITLE
Cleaning Undefined label warnings

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#159]
We get a TON of these on clean builds:

```
/_data/na-2017-day-1.json:1: WARNING: undefined label: 15-minute-talk (if the link has no caption the label must precede a section header)
/_data/na-2017-day-1.json:1: WARNING: undefined label: 5-min-switch-speakers (if the link has no caption the label must precede a section header)
/_data/na-2017-day-1.json:1: WARNING: undefined label: 15-minute-talk (if the link has no caption the label must precede a section header)
```

are they an unavoidable consequence of json/markdown? or can I fix by specifying Titles in either links or anchors? 

Also, these. Do we have to add years to links?

```
/home/samuel/Nosync/Repositories/WTD/www/docs/conf/eu/2016/index.rst:17: WARNING: Duplicate explicit target name: "videos".

```

**Comment by plaindocs** [comment]
I'm doing some background cleanup work in https://github.com/writethedocs/www/tree/sw-cleaning

**Comment by ericholscher** [comment]
Yea, that was from my janky hacks that automated linking from the schedule to the talk abstract. +1 to cleaning them up or doing it in a smarter, more data driven way :)

**Comment by plaindocs** [comment]
Running a build with sphinx 1.5.3 not the 1.3.6 in `requirements` also spits out an error related to awesome font:

```
WARNING: The config value `fontawesome_link_cdn' has type `str', defaults to `bool'.
```

**Comment by ericholscher** [comment]
Yea, I think that might be a bug with `ablog`. I should investigate more, but I don't think it's a real issue, as the config says it should be a string. http://ablog.readthedocs.io/manual/ablog-configuration-options/#confval-fontawesome_link_cdn

**Comment by plaindocs** [comment]
Marking this as done.
