### ISSUE TITLE
Broken Link on Origin Story page

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#1687]
Reported by @MarciaRieferJohnston in Slack:

```
FYI, I happened to discover a link on that page that no longer works. It's the one in this sentence: 
"The [experience](https://thoughtfuldrift.info/2013/04/11/write-the-docs-2013.html) was amazing."
```

I'm guessing that was a blog post.

* Simplest solution: remove the link
* Alternate solution: find a different blog post, or maybe link to pictures from 2013

**Comment by MarciaRieferJohnston** [comment]
@mjang Thanks for the suggestions, Mike. I've created a PR that swaps in a link to another blog post. Would you please approve it if you have the power to do so? See [PR 1688](https://github.com/writethedocs/www/pull/1688).

**Comment by mjang-cobalt** [comment]
Thanks @MarciaRieferJohnston ! I've approved and merged https://github.com/writethedocs/www/pull/1688, so I'm closing this issue.

**Comment by mjang** [comment]
Ack,I have two GH accounts :)
