### ISSUE TITLE
Speaker email calendar/reminders

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#1697]
We've got a bunch of emails in the repo now:

* the accept / rejection ones
* and 5 emails to the speakers throughout the process

We've also got a bunch of dates in the config. I reckon we'd only need to add a couple of other dates, or make some deadline choices relative to other dates (ie, send out the speaker email 04 two weeks before the video upload deadline) and we could quite easily generate `.ics` or some other reminder system (to me) about these, a week before the date.

Feels slightly like overkill, but also I'm juggling a lot of balls at the mo, and getting all the actions and dates lined up is not super trivial. 

@mxsasha you reckon this is easy enough to be worth doing?

**Comment by mxsasha** [comment]
I think the harder part is defining those dates - we tend to tweak those things a lot between conferences, or adjust their content. I am wondering if it would not be overengineering also considering the future of virtual is vague.

**Comment by plaindocs** [comment]
Yeah, I feel that side too. It's definitely not just a virtual thing though. And the adjusting is also part of what makes this useful...

If you load a calendar remotely from a URL, does it autorefresh on change I wonder?
