### ISSUE TITLE
Migrate WTD Quorum README to the Write the Docs website

### ISSUE THREAD

**Issue by barbaricyawps** [writethedocs/www#1730]
### Context for these changes

The Quorum pilot program was successful and now the Quorum program will officially be part of the Write the Docs meetup program. 😄  Now that it's official, we need to migrate some content from the [Quorum meetup repo](https://github.com/write-the-docs-quorum/quorum-meetups) to the Write the Docs website.

### Description of changes needed

Migrate the [Quorum README](https://github.com/write-the-docs-quorum/quorum-meetups/blob/main/README.md) file and turn it into a page on the Write the Docs website. The location of the new file should be:

**docs > organizer-guide > quorum.md**

Link to the old file: https://github.com/write-the-docs-quorum/quorum-meetups/blob/main/README.md

A few things to note:

- Some of the links on this README will require us to migrate other content from the quorum repository first. For now, remove any links that are internal to the quorum repository and we'll rebuild them later. Most of these kinds of links start with "See [link] for more information" or "For more information about [topic], see [link]."
- Remove the emoji in the headers.
- If you see references to my name (Alyssa), edit those out to make it something more generic like the Quorum meetup coordinators.
- As you are migrating this page, feel free to make improvements or link to other related pages within the Write the Docs website.

### Adding navigation to the new topic

Consider the best way to add this topic to the site navigation. Should it be in the side table of contents? Should it be a link from the main meetups index? You might have to make this judgment call.

### Contributing a PR to Write the Docs

In your PR, reference this issue and assign either @rosewms or @barbaricyawps as a reviewer.

**Comment by plaindocs** [comment]
~Is this just the README, or the whole repo?~ Never mind, saw the other issues. :+1: 

 And is there a preference for leaving it in markdown or converting it to RST?

**Comment by barbaricyawps** [comment]
No preference on my end. I love working in RST, but it might depend on whether the Writing Day attendees are familiar with it.

**Comment by barriebyron** [comment]
I'll grab this one for writing day

**Comment by plaindocs** [comment]
I think this is done.
