### ISSUE TITLE
Adapt the Quorum virtual event guide for general meetup use 

### ISSUE THREAD

**Issue by barbaricyawps** [writethedocs/www#1731]
### Context for these changes

The pandemic has made virtual Write the Docs meetups much more common, but virtual meetups require slight different strategies than in-person meetups. We can hopefully take some of the best practices developed in the Quorum meetup to create a guide for running effective virtual meetups.

### Description of changes needed

Create a new guide called "Hosting virtual Write the Docs meetups" or something similar. The location of the new file should be:

**docs > organizer-guide > virtual-meetups.md**

For the content of the guide, adapt and consolidate some of this content from the [Quorum repository](https://github.com/write-the-docs-quorum/quorum-meetups/):

- [Organizing a Quorum meetup](https://github.com/write-the-docs-quorum/quorum-meetups/blob/main/meetup-organizing.md)
- [Meetup roles](https://github.com/write-the-docs-quorum/quorum-meetups/blob/main/meetup-roles.md)
- [Zoom coordinator guide](https://github.com/write-the-docs-quorum/quorum-meetups/blob/main/zoom-coordinator-guide.md)
- [Emcee script](https://github.com/write-the-docs-quorum/quorum-meetups/blob/main/emcee-script.md)
- [Running a tech check](https://github.com/write-the-docs-quorum/quorum-meetups/blob/main/running-a-tech-check.md)

A few things to note:

- Some of the links might not work if they are internal to the Quorum repository. Remove those links if needed.
- If you see references to my name (Alyssa), edit those out to make it something more generic like the Quorum meetup coordinators.
- As you are migrating this page, feel free to make improvements or link to other related pages within the Write the Docs website.

### Adding navigation to the new topic

Consider the best way to add this topic to the site navigation. Should it be in the side table of contents? Should it be a link from the main meetups index? You might have to make this judgment call.

### Contributing a PR to Write the Docs

In your PR, reference this issue and assign either @rosewms or @barbaricyawps as a reviewer.

**Comment by rosewms** [comment]
This is great! 

We should encourage people to make a PR for each separate page listed and/or creating issues for individual pages to make the work more attainable.

**Comment by jeromefv** [comment]
Hey! I'm interested in tackling this one for a bit and seeing how to consolidate. Also happy to work with someone to either mentor if they're not as familiar, or take guidance if they've got other plans!

**Comment by jeromefv** [comment]
I'll work on the [Emcee script](https://github.com/write-the-docs-quorum/quorum-meetups/blob/main/emcee-script.md) to include!

**Comment by barriebyron** [comment]
I submitted https://github.com/writethedocs/www/pull/1743 for [Meetup roles](https://github.com/write-the-docs-quorum/quorum-meetups/blob/main/meetup-roles.md)

**Comment by jeromefv** [comment]
Following Barrie's PR, I've submitted [1745](https://github.com/writethedocs/www/pull/1745)

**Comment by barriebyron** [comment]
I submitted https://github.com/writethedocs/www/pull/1746 as a starter file for the organizer guide

**Comment by plaindocs** [comment]
Also calling this done.
