### ISSUE TITLE
Update the Starting a Meetup topic

### ISSUE THREAD

**Issue by barbaricyawps** [writethedocs/www#1732]
### Description of changes needed

We need some improvements to the [Starting a Meetup](https://www.writethedocs.org/organizer-guide/meetups/starting/) page (which is located in the repo at **docs > organizer-guide > meetups > starting.rst**).

NOTE: This topic is in reSTructured Text, not Markdown. For guidance on formatting content in rST, see:

- [reST & Sphinx cheat sheet](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/CheatSheet.html)
- [reStructuredText Primer](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)

Here's some suggested improvements:

- Near the top of the topic, add a link to the Meetup Coordinators team: https://www.writethedocs.org/team/#meetups
- In the section where you give the link to the coordinators team, mention that this team can be contacted for help with anything related to meetups such as: starting a new local meetup, retiring a meetup, setting up a Slack channel for a meetup, requesting access to the Zoom account, participating in the Quorum program, presenting at a meetup, and related questions.
- The headings aren't always consistent. Some end in colons (:) and those should be removed.
- Feel free to scan the content and make other general improvements that you see as necessary. Some of this content may have gone stale and needs to be removed or refreshed.

We have a [related issue](https://github.com/writethedocs/www/issues/1731) for creating a guide about hosting virtual meetups that could be integrated into the section about finding a location.

### Contributing a PR to Write the Docs

In your PR, reference this issue and assign either @rosewms or @barbaricyawps as a reviewer.

**Comment by miselainis** [comment]
I intend on working on this part of the project.
