### ISSUE TITLE
Update the Meetups and Covid page CDC urls

### ISSUE THREAD

**Issue by rosewms** [writethedocs/www#1734]
# Description

We need some improvements to the [Starting a Meetup](https://www.writethedocs.org/organizer-guide/meetups/starting/) page (which is located in the repo at **docs > organizer-guide > meetups > covid-19-meetups.rst**).

**Note**: This topic is in reSTructured Text, not Markdown. For guidance on formatting content in rST, see:

- [reST & Sphinx cheat sheet](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/CheatSheet.html)
- [reStructuredText Primer](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)

# Requested changes

Edit the Meetups and Covid page.

- Replace the CDC urls that 404
- Update the "last updated" date to current date
- Remove the following paragraph from the page:
 
> Therefore, CDC, in accordance with its guidance for large events and mass gatherings, recommends that for the next 8 weeks, organizers (whether groups or individuals) cancel or postpone in-person events that consist of 50 people or more throughout the United States.

## Contributing a PR to Write the Docs

In your PR, reference this issue and assign either @rosewms or @barbaricyawps as a reviewer.

**Comment by erinmadisonanthony** [comment]
working on this!

**Comment by Aysha-py** [comment]
Hello @rosewms , is this issue still opened?

**Comment by rosewms** [comment]
@Aysha-py let me double check the PR, thanks for the reminder.

**Comment by rosewms** [comment]
@Aysha-py thanks for following up, this work was completed in https://github.com/writethedocs/www/pull/1741
I'm going to close the issue!

**Comment by Aysha-py** [comment]
Okay Rose! Thanks for letting me know.. I would check other issues then
