### ISSUE TITLE
Update Meetup FAQ page

### ISSUE THREAD

**Issue by rosewms** [writethedocs/www#1735]
# Description

We need to review the [Meetup FAQ](https://www.writethedocs.org/organizer-guide/meetups/faq-meetups/) page (which is located in the repo at **docs > organizer-guide > meetups > faq-meetups.rst**).

**Note**: This topic is in reSTructured Text, not Markdown. For guidance on formatting content in rST, see:

- [reST & Sphinx cheat sheet](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/CheatSheet.html)
- [reStructuredText Primer](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)

# Requested changes

* This needs a general review for style, grammar, and punctuation.
* Edit the "Anything else I get for organizing a meetup?" section header to "Meetup organizer benefits"

    * Edit the section and add the following benefits: 50% off conference tickets, community organization 
     experience, volunteer experience, resume builder, organizer sessions at conferences.

## Contributing a PR to Write the Docs

In your PR, reference this issue and assign either @rosewms or @barbaricyawps as a reviewer.

**Comment by KyleBlankRollins** [comment]
I intend to work on this for Writing Day.
