### ISSUE TITLE
Broken links in RTD GA action

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#1827]
The preview URL from https://github.com/writethedocs/www/pull/1791 is actually broken,

`https://writethedocs-www--1799.org.readthedocs.build/en/1799/` needs the `/en/1799/` chopping off.

**Comment by ericholscher** [comment]
Yea, I opened an issue about this on the GH action, will try to get it resolved.

**Comment by plaindocs** [comment]
@ericholscher any update? Wanna past a link to the issue here?

**Comment by ericholscher** [comment]
It should be fixed now. I'll open a PR.

**Comment by ericholscher** [comment]
https://github.com/writethedocs/www/commit/2c765caa59290ecbb95c400606adbbfdc093222f should fix it 👍
