### ISSUE TITLE
Add `venv` to readme info

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#191]

**Comment by plaindocs** [comment]
```
sudo apt-get install virtualenv
virtualenv VENV
source VENV/bin/activate
pip install -r requirements.txt
```

Then remember to activate it! :-p

**Comment by plaindocs** [comment]
@ericholscher -> does that look about right? Or should I use tox so we can reuse the environment? 

Does python2 usually include virtualenv?

**Comment by ericholscher** [comment]
Python3 and perhaps 2.7 ship w/ `venv` in the standard lib, letting you do `python -mvenv env` I believe. It's complicated, and the above wouldn't work on redhat based distros, but there's not really a good solution. Could also link out to the virtualenv install docs, but mentioning something will work for now.
