### ISSUE TITLE
Text overflow on smaller screens

### ISSUE THREAD

**Issue by ironnysh** [writethedocs/www#1931]
Hi there,
When browsing the site on an iPhone SE (320 pixels wide), I noticed the text overflows and creates a horizontal scroll.

The culprit is the `min-width` CSS property on the `body` class (defined in basic.css that's imported in alabaster.css):
```
div. body {
min-width: 450px;
}
```
![overflow](https://user-images.githubusercontent.com/63248335/230713658-e5117ddb-b738-4e29-be35-f917c17f4aef.jpeg)

Removing this line, or setting a narrower minimum width (preferably using responsive units, such as `em`, `rem`, or `ch`) solves the problem:
![no-overflow](https://user-images.githubusercontent.com/63248335/230713656-5ed6a687-2e6a-4334-be30-b3de6c84ec6d.jpeg)

**Comment by plaindocs** [comment]
Hey @ironnysh thanks for reporting! 

@ericholscher @goatlady can we safely delete this? Or if not what minimum width should we be setting?

**Comment by goatlady** [comment]
I agree that min-width shouldn't be fixed at 450px - I would expect that would be overridden in a breakpoint below 450px. Just removing it does cause some issues with the footer, looks like there's some kind of scaling that kicks in below a certain size, so perhaps setting `min-width: 320px` would fix the immediate issue on mobile and we can test further?
