### ISSUE TITLE
Add a site-map link to the home page for the mobile UX

### ISSUE THREAD

**Issue by MarciaRieferJohnston** [writethedocs/www#1941]
Since small screens don't show this site's nav panel, it's hard for visitors to get the lay of the overall content from the home page. If you add a site-map link to the home page, we'd have access to that big picture: a high-level view of all the treasure just waiting for us to dig for.

I didn't create a PR since I'm not sure the best way to do this. 

- Add a hamburger menu that brings out a basic table of contents?
- Add a site-map link at the bottom of the home page? 
- Add the site-map link in a footer so that it's available on every page? I like that idea. 

If you like the footer idea too, how about including a topic-index link too? That way, from any page, we can "flip to the front" (table of contents / site map) or "flip to the back" (index), depending on the kind of exploring we want to do.

**Comment by plaindocs** [comment]
Hi @MarciaRieferJohnston 

I'm not quite sure what you're looking for beyond the structure in the expanded menu? 

![photo_2023-05-01_13-00-31](https://user-images.githubusercontent.com/95874/235521070-4b17ae2b-6b34-45da-94d4-04b48b15946b.jpg)

Or do you mean per page? 

That menu I show admittedly needs re-styling, and left aligning and probably some other tweaks.

**Comment by marciarjohnston** [comment]
@plaindocs Hi, Sam. Thanks for the screenshot of the Portland conference home page (https://www.writethedocs.org/conf/portland/2023/). Style details aside, that's exactly the kind of thing I'm looking for but for the home page of the overall site: https://www.writethedocs.org/.
![IMG_1304](https://user-images.githubusercontent.com/60661686/235528315-c9bdfe5f-367e-4097-99d8-4ccd3dd31a0f.PNG)

**Comment by plaindocs** [comment]
Oh yeah, I'm with you now! My brain is firmly in Portland conference space right now, and jumping to unwarranted conclusions. Let me see what I can do about that.

**Comment by MarciaRieferJohnston** [comment]
@plaindocs Nice to finally meet you in Portland, Sam. Please let me know if you have any other questions or thoughts on this request.

**Comment by plaindocs** [comment]
Likewise @MarciaRieferJohnston 

I've not, it's been pretty chaotic coming back from Portland, wrapping up the CFP for the online Atlantic conference and most recently ducking out for a week of hiking. 

However, it is on my mind, and basically involves partially reverting the landing page reorganization I made in https://github.com/writethedocs/www/blob/main/docs/index.rst?plain=1 in this simplifcation pull request https://github.com/writethedocs/www/pull/1814 .

What we need to do is keep the simplificaiton, but migrate it back to a toctree with custom page names I believe. I'll get to it, but feel free to have a noodle if that's something you'd like to see sooner, and do ask if you've got questions.

**Comment by MarciaRieferJohnston** [comment]
Sounds good to me, Sam. Thanks.

**Comment by MarciaRieferJohnston** [comment]
P.S. Thanks for all that you've been doing since the Portland conference (and at that conference). Hope you had a splendid and rejuvenating hike.

**Comment by plaindocs** [comment]
I started looking at this in #1971
