### ISSUE TITLE
Incorrect Slack URL?

### ISSUE THREAD

**Issue by MattDodsonEnglish** [writethedocs/www#2009]
A URL for `http://slack.writethedocs.org` appears in various texts on the site. You can find occurrences by going to the directory root and running this command: 

```bash
grep -ir "slack\.writethedocs\.org" .
```

As far as I can tell, this link is broken and should be updated to `https://writethedocs.slack.com`. I'm happy to make the fix myself, but I just wanted to make the issue first in case I'm missing something.

**Comment by plaindocs** [comment]
Hi Matt,

Thanks for noticing! I'm pretty sure that is human error. @ericholscher did you change this in living memory? 
Regardless, a fix would be most welcome. :-)

**Comment by MattDodsonEnglish** [comment]
I found the old URL in commits as [early as 2016](https://github.com/writethedocs/www/blame/bab2780e2876bfedce12d14422f34e9143c945ff/docs/blog/newsletter-november-2016.md#L16). But it also appears in commits as late as 2022. Also, by rough calculation (piping grep to `wc -l`), the incorrect URL appears three times more often than the current URL.

For these reasons, I thought I might be missing something. My guess is that that URL used to be valid and it continues to propagate through renaming,  template copying, and occasional muscle memory.

>  Regardless, a fix would be most welcome. :-)

Cool, I'll make the changes soon.

**Comment by plaindocs** [comment]
Sounds extremely believable.

**Comment by ericholscher** [comment]
slack.writethedocs.org  used to be a web app that let you register for Slack, and then a redirect to https://www.writethedocs.org/slack/, which is likely where most of those links should point.
