### ISSUE TITLE
Meetups: What should organizers do during the meetup

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#218]
1) Greeted everyone who came
2) Via slides, introduced the meetup
3) Gave everyone a few sec to talk about themselves and the theme
4) Used the help she had, for working the AV, in making sure the speakers were ready
5) Introduced each of her panelists in a way that boosted their confidence
 
(also CoC)

**Comment by lleonard-msft** [comment]
@mjang - Do you think we're ready to close this issue?

**Comment by mjang** [comment]
Thanks for your help @lleonard-msft !
