### ISSUE TITLE
Process to onboard new contributors

### ISSUE THREAD

**Issue by meker12** [writethedocs/www#220]
Readme does not provide instructions for Windows users.

Workflow -- When do we add contributors to team|collaborator| list, and when do we just force fork when someone commits a change.

**Comment by annegentle** [comment]
@meker12 We are working on this today on a Windows computer, and @HeatherAtiFactor is testing. I'll help her with the PR.

Can anyone assign her to this Issue?

**Comment by plaindocs** [comment]
Awesome! No need for formal assignment, the comment above should stop anyone else from picking it up.
