### ISSUE TITLE
Slack link is expired

### ISSUE THREAD

**Issue by bpmct** [writethedocs/www#2238]
Hey folks - hoping to join the Slack but sadly the link from [this Google form](https://docs.google.com/forms/d/e/1FAIpQLSdq4DWRphVt1qVqH8NsjNnS0Szu_NljjZRUvyYqR7mdc00zKQ/viewform), linked from [this site](https://www.writethedocs.org/slack/) is expired as of Oct 2

https://github.com/user-attachments/assets/2975400d-58cd-4a1c-bad7-8f907f714eeb

**Comment by plaindocs** [comment]
Hi Ben, that link should be updated.

https://join.slack.com/t/writethedocs/shared_invite/zt-2rkpnus2v-pe14ATkvuuX7UCK6iMibUw
