### ISSUE TITLE
Slack join link after filling out form is no longer active

### ISSUE THREAD

**Issue by daneah** [writethedocs/www#2250]
I would love to join the Slack community, but I filled out the form and the link that it gave me after doing so resulted in this page:

<img width="624" alt="Screenshot 2024-11-01 at 09 28 56" src="https://github.com/user-attachments/assets/bcf7d20a-1166-4742-b310-890d9ef87b77">

**Comment by plaindocs** [comment]
Hi @daneah please join using https://join.slack.com/t/writethedocs/shared_invite/zt-2tnx1bx7p-mvGybEVuic01MXvOkCVopA

**Comment by daneah** [comment]
Thanks @plaindocs!
