### ISSUE TITLE
Process discussion from WTD '17 meetup-organizer session

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#232]
![wtd_unconf](https://s3.amazonaws.com/uploads.hipchat.com/46528/328785/ofwQzMcHdtypg0w/IMG_20170515_143115.jpg)

**Comment by mjang** [comment]
I'm thinking a wiki might encourage collaborative answers to these topics. (I'm mentally thinking -- maybe that'd be the best way to direct IO from a meetup-organizers chat?) @ericholscher can you suggest something we can use?

**Comment by plaindocs** [comment]
Let's try to keep stuff out of Eric's plate unless we need to do. What are your requirements? 

We want input from Meetup Organizers every 3 (4? 6?) months on:

* x
* y
* z

And what do we want to do with the info? Store it? Privately? Publicly?

**Comment by ericholscher** [comment]
I like etherpads for this. eg https://public.etherpad-mozilla.org

**Comment by mjang** [comment]
Unfortunately, I no longer have access to the linked notes (the link goes to a 403). I think we should close this issue.
