### ISSUE TITLE
Set up / schedule remote meetup leader roundtable session

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#235]
Plan: quarterly online remote session, using a tool such as Google Hangouts

**Comment by mjang** [comment]
Open question -- given time zone differences, is it more practical to limit the online remote session by geographic region (e.g. North America, Europe -- and early/late enough to allow our Asian and Australian meetups to join)

**Comment by ericholscher** [comment]
:+1: on regional meetups

**Comment by plaindocs** [comment]
I suspect making it a 3 line update via email, and scheduling a call if *anyone* wants it makes sense as well.

**Comment by mjang** [comment]
@cwcromwell During this year's unconf session, you talked about using GoTo Meeting to set something up. May we assign this issue to you?

**Comment by cwcromwell** [comment]
Yes. I'd like to help with this. I had to put it on the back burner for a bit because I had a lot of irons in the fire. We should chat a bit about: 
-objectives
-frequency
-target audience (noobs versus all organizers)

**Comment by mjang** [comment]
Thanks @cwcromwell . I've invited you to the list of allowed assignees, and will add you as such as soon as you accept.

My opinion

Objective:
1) Spread the word that we're available for each other
2) At the first session, round table intros
3) Get a list of objectives for future sessions

Frequency:
My guess, once / quarter or half-year is a reasonable goal.

Target Audience:
Limit to meetup organizers (and meetup organizer wannabees)

**Comment by plaindocs** [comment]
I think this is happening, and as such we can close the issue.
