### ISSUE TITLE
Include a list of slide decks from WTD NA 2017

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#236]
For now, I'll leave them in comments (and invite others to do the same)

Jodie Putrino: (Docs like Code) http://preview.tinyurl.com/k4fqkzo
Kate Voss: (Error Messages) https://docs.google.com/presentation/d/1gCgkaaXIFSLf3afRxEGNFwm0bPTcURcVQNuQj0QZDqQ/edit
Sam Faktorovich: (Hiring techincal Tech Writers in Siberia) https://speakerdeck.com/factorized/hiring-technical-writers-the-siberian-way

**Comment by amzn-tomjoht** [comment]
Tom Johnson: [Building navigation for your doc site: 5 best practices](http://idratherbewriting.com/files/doc-navigation-wtd/index.html)

**Comment by plaindocs** [comment]
This is a good call. We should probably look at including it in the speaker data file, so we can add it to the session info after the conf.

**Comment by mbuttler** [comment]
Matthew Buttler: [Only Interesting Conversations: The Symbiotic Relationship Between Documentation and Support](https://docs.google.com/presentation/d/1JpyWi6uN-3zhM77ApzVz15jUw_8dckEh1Hs6dhsac2o/edit?usp=sharing)

**Comment by jseldess** [comment]
Jesse Seldess: [Bootstrapping Docs at a Startup](https://docs.google.com/presentation/d/1Sce3OtXMF2mUV11taCqNzXERdsFBtfdxBXYqs7EBI_k/edit?usp=sharing)

**Comment by loispatt** [comment]
Not my slides, but thanks to Andrea Longo for this talk: 
[Do you know a runbook from a flipbook? How sysadmins use documentation](http://feorlen.org/wtd/index.html)

**Comment by loispatt** [comment]
Again not mine. Christy Lutz: [You have already succeeded: Design critique guidelines make feedback easier](http://canncrochet.com/Presentations-1)

**Comment by plaindocs** [comment]
Thanks people! 

@ericholscher I think I'll add a slide key to the json (cough yaml), much as with the videos, and add a link to speaker pages as a first step. then we can factor it in to Leo's work when that is coming in.

Thoughts?

**Comment by ericholscher** [comment]
Works for me. Leo's work will need some focus for a few days to get it deployed, but I'm excited about it.

**Comment by mjang** [comment]
Sarah Hersh: https://docs.google.com/presentation/d/1I9FwgeRD0JvkikuQqf64fncvlK_YwxOpmDdoS1oSTQQ/pub?start=true&loop=false&delayms=60000#slide=id.p

**Comment by rainbowkenz** [comment]
Kenzie Woodbridge: Everyone's a player (in a mid-90s MUD) https://docs.google.com/presentation/d/16lt-az4HyfWOg4k-HxbH2rhfmC5q6dC9Nuy0Exb3VYU

**Comment by anzelpwj** [comment]
Paul Anzel - The Science(?) of Documentation lightning talk: https://github.com/anzelpwj/writethedocs2017

**Comment by IngridT** [comment]
The Wisdom of Crowds: Crowdsourcing Minimalism in an Open Organization
Ingrid Towey, Aneta Šteflová Petrová, Brice Fallon-Freeman
https://docs.google.com/presentation/d/1Yeql9FrRBgKU-QlRU-nblPJ9pfZKgoKcU8SW6SQ_UqI/edit?usp=sharing

**Comment by loispatt** [comment]
Again not mine. Carl J. Parker: https://github.com/carljparker/wtd-2017-verifiable-crisis

**Comment by unruthless** [comment]
Ruthie BenDor - Even Naming This Talk Is Hard (now with speaker notes!)
https://www.slideshare.net/unruthless/even-naming-this-talk-is-hard

**Comment by plaindocs** [comment]
These are all live on the speaker page, so I'm closing this.
