### ISSUE TITLE
Non Python doctests with Sphinx: try/explain "manuel" recipe

### ISSUE THREAD

**Issue by benoitbryon** [writethedocs/www#24]
Seems to be possible to have non Python (sh, ruby...) doctests in Sphinx documentation with [manuel](https://pypi.python.org/pypi/manuel) software.

See zopefoundation/zdaemon test suite on Github for examples.

**Comment by xmo-odoo** [comment]
As far as I can see, [the zdaemon test](http://github.com/zopefoundation/zdaemon/blob/master/src/zdaemon/tests/tests.py) are Python docstrings, but these docstrings run other stuff via `system()`. Manuel doesn't seem to support non-python tests anymore than Sphinx itself does.
