### ISSUE TITLE
Missing page about linters?

### ISSUE THREAD

**Issue by wilburnvanessa** [writethedocs/www#245]
Today, I found a Google hit for the following page:
https://write-the-docs.readthedocs.io/guide/tools/linting/

But when I take the link from the Google search page, I get a 404. This page looks like it would be great to see, but it's not currently available. Screen capture of the search results is below. 

Thanks for sharing great info on the site!

![screen shot 2017-06-07 at 11 29 25 am](https://user-images.githubusercontent.com/13280280/26889706-99b8e858-4b74-11e7-98af-fa04032b2588.png)

**Comment by jdkato** [comment]
It looks like the content of that page was moved to https://write-the-docs.readthedocs.io/guide/tools/testing/#style-guide-checking-and-linting in commit b80c46147dc9b23c05272846d655e3bff285e646.
