### ISSUE TITLE
Add to Meetup FAQ: What happens w/moves from Basic -> Unlimited subscription plans

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#296]
Some meetups have started with the "Basic" subscription plan, and have grown quickly. 

When the meetup -> 50 members, Meetup is supposed to prompt the organizer to upgrade to the "Unlimited" plan. 

Based on Meetup.com feedback to a WtD meetup organizer, "If you decide to upgrade your subscription plan, you will not be charged for that upgrade until your next renewal date.

In other words, if you upgrade now, you can begin accepting new members right away, but you won’t be charged at the Unlimited rate until your subscription renews on <date redacted>."

**Comment by mopdx** [comment]
I would like to do this one. mopdx

**Comment by mopdx** [comment]
Checked with Mike Jang and Sam. Changes OK'd (added "Basic vs. Unlimited meetup subscriptions" section, which paraphrased the member/organizer differences and Unlimited rate not kicking in until renewal date.
