### ISSUE TITLE
Links to NYC and Philly meetups are missing from the Meetups page

### ISSUE THREAD

**Issue by NickVolynkin** [writethedocs/www#361]
http://www.writethedocs.org/meetups/

[Markup] presumes that links to these meetups should be added to sidebar, but the [sidebar template] doesn't seem to render toctree.

[Markup]: https://github.com/writethedocs/www/blame/master/docs/meetups/index.rst#L49
[sidebar template]: https://github.com/writethedocs/www/blob/master/docs/_templates/navigation.html

```
.. toctree::
   :maxdepth: 2
   :hidden:

   nyc
   philly
```

**Comment by plaindocs** [comment]
I think with the new restructured sidebar with less links this isn't relevant. Thanks for raising Nick.
