### ISSUE TITLE
Final bits of post-launch website fixes

### ISSUE THREAD

**Issue by thatdocslady** [writethedocs/www#367]
This is an attempt to aggregate all the leftover fixes following the amazingly-awesome new website launch :)

- [x] The Tickets page has different color scheme for the actual ticket descriptions. Previously it was raw HTML, and now @plaindocs submitted a PR to convert it to RST (#369) but we need some design help to change the colors (from whatever brown-orange) to something that matches the website.

- [x]  Now that the H2, H3, H4 titles are black and have different sizing, the H1 (white text over the header image) looks a bit small. Maybe consider making it bigger? There's space for it.

![screenshot from 2017-11-20 08-54-50](https://user-images.githubusercontent.com/6662054/33119130-52fbe0f4-cf6e-11e7-94f8-8fc59d62dc80.png)

- [x] Update sponsorship related CSS to include the *five* levels in http://www.writethedocs.org/conf/portland/2018/sponsors/prospectus/ 

- [x] Navigation bar needs restructuring and drop-down entries for some items. All of the linked pages should exist already in the repository.
- [x] Somehow the logo is smaller now on the home page, not sure what happened there ;)
- [x] Text in "can't wait for the conf..." and "join us now" is not vertical-center aligned with the pane that it's in (the buttons are aligned, for comparison).
- [x] The "Speak" button has white text over bright green, which makes it harder to read, maybe change the text to black, or change it to an outline box instead of fill? Not sure what's the optimal solution here.

**Comment by plaindocs** [comment]
Thanks for driving this @thatdocslady 

These all look relevant to me. I can convert the HTML to RST in the tickets, don't know if any part of of that is an automated export from Tito? Doesn't really matter I guess.

**Comment by thatdocslady** [comment]
Ok @plaindocs I'll move the ticket issue to the Trello card so we can fix it ourselves (yourself? <3), and I'll pass this issue onwards to Leo now so that he can help with the rest.

**Comment by plaindocs** [comment]
Or just leave it there @ assigned to me?

**Comment by xpostudio4** [comment]
The text is really aligned with the buttons as you can see here.

![picture](https://user-images.githubusercontent.com/755375/33301634-1aac3114-d3cd-11e7-82fc-07996b4f745a.jpg)

**Comment by thatdocslady** [comment]
@xpostudio4 thanks for all the fixes so far! I checked the items that were solved in the PR that you submitted, please review the remaining items and let us know whether it's something that can be resolved.

Regarding your reply about the buttons, firstly in your screenshot it still looks misaligned (see the line on the far right button), and also the buttons that you see are not the same as what I see in the actual website (or in the Netify preview). Here's a screenshot of what we have:

![screenshot from 2017-11-29 15-16-41](https://user-images.githubusercontent.com/6662054/33379773-46c2a1fa-d519-11e7-897d-5ad9d022af09.png)

You can see that the *bottom* of the text is aligned, but because of difference in fonts and capitalization, the *top* of the text isn't the same. I realize this might be a little detail-oriented, but it really bugs my eyes and it's such a nice layout/color scheme that if we can make it work it'll be lovely.

Thanks again!

**Comment by ericholscher** [comment]
@thatdocslady not sure I understand the 5 levels sponsorship CSS one?

**Comment by thatdocslady** [comment]
Thank you @xpostudio4 for all the fixes! Closing this issue and calling website DONE :)
