### ISSUE TITLE
Content side post launch fixes

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#368]
- [x] Proofread content in all newly-navigatable pages (now that the menu includes them)
- [x] Tweak navigation links (some menu items link to the wrong pages)
- [x] Link to sponsorship prospectus is broken
- [x] Tickets page fixes (also applies to Speakers page, TBD)
- [x] Fix CSS of logo hyperlink from blue > black
- [ ] heading of sponsorship prospectus is too long so it runs down to the edge of the image: 
![screenshot from 2017-12-13 14-50-03](https://user-images.githubusercontent.com/6662054/33942147-470a0cd2-e015-11e7-92f0-e04960469119.png)

**Comment by thatdocslady** [comment]
Added new items to description to fix/verify. @ericholscher do you mind taking a look at these? Thx!

**Comment by ericholscher** [comment]
What is the proposed fix for the sponsorship page?

**Comment by thatdocslady** [comment]
I'd say either enforce a character limit on titles (not so practical) or shift the titles up so that there is more of a margin between the bottom of the text and the bottom of the image. The latter will of course affect all the other titles, but it shouldn't be a problem. I don't know exactly how many pixels we'd need to move the titles, might need to experiment a bit.

**Comment by plaindocs** [comment]
I think you're talking apples and oranges here.

I'm not sure there is a fix for the sponsorship page.

**Comment by ericholscher** [comment]
I also think there isn't a real issue with it. If we have an issue, perhaps we should just change the page title to something shorter?

**Comment by plaindocs** [comment]
We could presumably lint the title to warn if we have too many chars :-D

**Comment by plaindocs** [comment]
Are we actually using the PDF version of this page? If so something like 

```
.. only:: html

   Sponsorship - Portland 2018
   ###########################

.. only:: pdf

   Write the Docs Portland 2018 Sponsorship
   ########################################
```

otherwise just change the title? 

@ericholscher @thatdocslady

**Comment by ericholscher** [comment]
Doubt it. I just printed the HTML page as a PDF when I needed a PDF :)
