### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by westurner** [writethedocs/www#376]
HTTPS for the writethedocs.org domain is currently broken.

https://www.writethedocs.org/guide/

- https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl
- https://github.com/rtfd/readthedocs.org/issues/888

A write-up on how to do CloudFlare HTTPS and HTTP STS with readthedocs.org would be super helpful.

https://LetsEncrypt.org certs are an alternative solution, but those must be regularly rotated.

**Comment by westurner** [comment]
> A write-up on how to do CloudFlare HTTPS and HTTP STS with readthedocs.org would be super helpful.

It's probably not very different from the GitHub Pages CloudFlare setup?

https://github.com/rdfjs/rdfjs.github.io/issues/1#issuecomment-204642018

@ericholscher
Is the ``X-RTD-SLUG`` header required for CloudFlare SSL? HTTPS with custom domains is a very common need/concern.

https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl

**Comment by plaindocs** [comment]
This is fixed now. Thanks for reporting @westurner

**Comment by westurner** [comment]
Thanks!
