### ISSUE TITLE
Update bios for conference staff

### ISSUE THREAD

**Issue by thatdocslady** [writethedocs/www#381]

**Comment by thatdocslady** [comment]
@plaindocs is this task for all staff? I'm just updating for Prague, and not really touching existing bios, only adding new ones.

**Comment by plaindocs** [comment]
Dunno :-p you opened the issue ;-)

I'd close it when you're done adding new staff for Prague.

**Comment by thatdocslady** [comment]
Did I?

**Comment by thatdocslady** [comment]
Did I?

**Comment by plaindocs** [comment]
> thatdocslady opened this Issue on Dec 1, 2017 · 4 comments 

> thatdocslady opened this Issue on Dec 1, 2017 · 4 comments
