### ISSUE TITLE
Generify generic content

### ISSUE THREAD

**Issue by thatdocslady** [writethedocs/www#382]
Some content can be extracted to an /include/ folder and reused throughout the conference websites.
Example can be found in the source file for: http://www.writethedocs.org/conf/portland/2018/writing-day/ 

Things to keep in mind:

- Title tag conventions (H1, H2, etc)

**Comment by plaindocs** [comment]
@thatdocslady Can we call this done?

**Comment by thatdocslady** [comment]
Not yet, I still need to do another passthrough of the websites and see if other chunks need to be moved. Next week probably!

**Comment by plaindocs** [comment]
@thatdocslady Can we call this done? :trollface:

**Comment by thatdocslady** [comment]
Oh yes! For now we’re good :)
