### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by benoitbryon** [writethedocs/www#4]
Fill in LICENSE file, so that things are clear.

**Comment by benoitbryon** [comment]
What about a [fair license](http://opensource.org/licenses/fair)?

Or creative commons maybe, since this is more about content than about software.

I personally don't care much about the license, provided it is open source (public domain, beerware or wtfpl are also ok for me).

**Comment by ericholscher** [comment]
Agreed. Can you use BSD/MIT for docs? We should add a license, and then document what licenses are good for docs :)

**Comment by benoitbryon** [comment]
> document what licenses are good for docs

Added #6 about it (could be done later).

**Comment by benoitbryon** [comment]
> Can you use BSD/MIT for docs?

I don't know. They talk about "software". Moreover, there are some specific licenses like "FreeBSD documentation license" or "Gnu free documentation license", which makes me bet that standard FreeBSD or GPL doesn't fit documentation needs (but I really don't know the details).

Does someone know more on this topic?

Else, imho, "Fair license" sounds simple and open. May be enough to start.

And "Creative commons" seems alright to me too: isn't docs.writethedocs" a (static) website written by a community"? As a documentation, it looks like an community-written online book (or a wiki perhaps), rather than a collection of articles written/owned by respective authors. We could use it if we want some features like "share alike" or "CC BY".

**Comment by thoward** [comment]
+1 on CC

**Comment by ericholscher** [comment]
Cool. I'm fine with a CC license, or the BSD docs license sounds good to me
too (Since I normally BSD my code)

On Mon, Jan 28, 2013 at 1:34 PM, Troy Howard notifications@github.comwrote:

> +1 on CC
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/writethedocs/docs/issues/4#issuecomment-12806105.

## 

Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by ericholscher** [comment]
http://creativecommons.org/licenses/by/3.0/ maybe?

**Comment by benoitbryon** [comment]
+1

**Comment by benoitbryon** [comment]
Closed by commit 9d97c91
