### ISSUE TITLE
Confusing meetup requirement

### ISSUE THREAD

**Issue by paulwicking** [writethedocs/www#411]
I got a little confused when reading the [organizer guide](http://www.writethedocs.org/organizer-guide/). The page links to [community events](http://www.writethedocs.org/organizer-guide/confs/community-events/), which lists types of events and requirements to run one. Meetups are listed as such an event, and the requirements state that any community event 

> Must have multiple organizers from more than one company, and organizers must be listed on the website

I asked @thatdocslady how I could meet this requirement when starting a WTD meetup in a new location. In my case, there's not even a WTD in a neighboring country. She seemed as befuzzled as I about this and suggested I open an issue to address this.

**Comment by plaindocs** [comment]
The intent here is that events need to be 'vendor neutral', not organised by one company, held in the premises of the same company, and publicised internally. 

If you're starting a brand new meetup, don't worry about it over much, and once you've got a few more members, ask one of them to join you as co organiser.

**Comment by plaindocs** [comment]
I'll have a look at the requirements again, and attemp to clarify.

**Comment by paulwicking** [comment]
I get the intent, and I agree it is something to strive for. But as a requirement for getting things off the ground, it puts the bar at a disheartening height. Clarifying this is probably a good idea.

**Comment by plaindocs** [comment]
@ericholscher has added a note to resolve this in 32b8db4f7
