### ISSUE TITLE
2018 GRORG -> FORMS -> YAML workflow

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#421]
What I understand of our workflow up till now goes something like this:

1. `conferences.py` in CFP repo to produce a `speaker.yaml` from Grorg, massaged  for multiple speakers somehow. I'm still not entirely clear how this works at all. 
2. tweaked `csv.sh` to generate detailed schedules, run locally on data exported from sheets. 

Current workflow is more like 

1. Pre selection in Grorg
2. Final list in Sheets
3. Google form for accepted speakers with more info (such as promo tweet, updated abstact and pic - not sure if we can easily autosave those)
4. No change in the schedule flow

Saving from Google Sheets to **TSV** (because csv does not like the long text abstracts somehow) and then

```
cat wtd.tsv | cut -f 2,4,5,6,7,9,10 | csvjson -t -I -i 4 | python -c 'import sys, yaml, json; yaml.safe_dump(json.load(sys.stdin), sys.stdout, default_flow_style=False)'
```

Gives us some approximation of yaml, although some work still needed, especially regarding multi speakers.

We prob need to do a sheet lookup to get the name back from the original CFP form.

**Comment by plaindocs** [comment]
I suspect we might be better off rethinking the google form approach, or at least sticking to the initial Grorg export and then adding the form data semi manually. 

Thoughts?

**Comment by ericholscher** [comment]
Is there a primary key (eg. name) on the secondary google form that lets us map it to their talk? We only have ~20 speakers, so doing stuff manually isn't hard, but shouldn't be necessary.

**Comment by plaindocs** [comment]
The intention was to use the email for that.
