### ISSUE TITLE
Process discussion of imposter syndrome among writers

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#437]
Anonymized transcript here: https://gist.github.com/mjang/c49474fb7bbccbf06a9f47e7db096456

**Comment by ElinaMcC** [comment]
Elina here, participating in Write the Docs Vilnius 2019. I'm going to grab this great mass of interesting text, ideas and synthesis, and work it into something that can potentially be published on writethedocs.org. I can't assign the issue to myself atm.

**Comment by plaindocs** [comment]
Fixed by #962
