### ISSUE TITLE
Add sanity checking and error prevention to the video archive

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#442]
Post merge fixes needed for #393 the most obvious of which are:

- [ ] Not generating video pages for confs till after we have videos. Best would be to add a check for boolean `hasvideos` in the conf config file for 2018 and up.
- [ ] If data file doesn't have `youtubeId` keys the index is empty. Would be best to not generate / include these. 

Also, I'm not quite sure what the status of meetup videos and lightning talks is. :-p

**Comment by mxsasha** [comment]
Is this actually still an issue? I don't think I've run into it at all.

**Comment by plaindocs** [comment]
2018?
