### ISSUE TITLE
Lessons learned from WtD meetup on Hiring

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#444]
Based on the March 6 Meetup for WtD PDX, with 6 lightning talks. Find someplace to write up for writethedocs.org. Probably ask for input from the other speakers.

My lessons learned, from the #career-advice channel:

mikejang [9:01 PM]
Re Documentarian job skills: we just had 6 lightning talk speakers at our WtD PDX meetup on the subject (aka -- "If you needed to hire a new writer.") (Sorry, no video -- and only 3 of us had slide decks).

But there were recurring themes:

1) Be bold. Own what you do. 
2) Command line skills are frequently essential -- and are not out of reach for the non-technical
3) Know how to deal with strong personalities
4) "Stupid questions" frequently lead to unexpected answers (aka why they're not stupid)
5) Be willing to build expertise in specific technical subjects (relevant to your target companies) -- some are willing to hire if you have expertise in areas not even be in the job description.

Hello! Recent grad here (English major, Tech Writing/IT minors) - I'm thinking I should take some online classes while I'm looking for a tech writing job to broaden my skill set. In my last role, knowledge of MadCap Flare, TortoiseGit, HTML, and CSS was required. I also have foundational academic-level exposure to Java/Python. Does anyone have suggestions for additional tools/languages/concepts that would be useful? My experience is limited to end-user documentation, and I'd love to know how some of you acquired the knowledge/skills needed to shift toward writing API/SDK docs. (shoutout to @mikejang for referring me to this channel)

mikejang [9:21 PM]
The big bit for me from our meetup -- there are others with desirable jobs who are big on writers who know the command line interface. For us, it's Unix/Linux command line skills.

@mikejang what level of Linux CLI skills are expected from writers? I can find my way around the command line in putty, do builds, change file permissions, and other basics, but I'm not sure that's what you're talking about here.

I don't have any Linux at all.  I would say it all depends on the company and the writing job.  I use command line for git in a windows environment.  Knowing a bit about some of the jobs available in my area (Yorkshire, UK) I think that knowledge of git and an authoring product/method such as DITA, Markdown with Jekyll, Madcap Flare, Adobe Technical Communications Suite or AuthorIt would be more desirable.  We use CLI but all our jobs are automated and managed by our DevOps team. If there is an issue they deal with it  The most taxing thing I need to do is open a page in my browser and press a button to launch a build or deployment pipeline, where it is set to manual.  My main work is deployed automatically. (edited)

A lot of Technical Writers branch out into different areas.

I make use of UNIX CLI everyday, but that’s my specialty.

Indeed, it all depends what direction you want to go in.  Also you need to look at the job descriptions for jobs on offer in your part of the world.  I basically developed the skills I needed to stay employed in Yorkshire.  In another area I may have needed a whole different skill set.

I agree with 
From my experience, it was always important to know my way around the creation and maintenance of my content (DITA, XML, CCMS). I always could rely on experts that got my stuff published, never had to do the scripting for that myself.
But it never hurts to be open-minded about the tools that your testers and developers are using (Git, SoapUI, ...) 
You gain a better understanding of their daily work and they'll be more willing to accept you in their team :slightly_smiling_face:

@mikejang - I’m curious. How are writers using the CLI? I’m comfortable with it because I learned about PCs in the age of DOS, but I suppose you’re referring to PowerShell or Bash commands? I have limited use for it in my current job, but it seems to be the preferred method for working with git repos.

 I can answer that question for a different use case from Mike's -- I help document Kubernetes, which means I'm on the command line (bash) with command-line tools for aws, gcp, azure, kube itself, plus the cli for the open-source tools that my company contributes to the Kubernetes community. Plus git, yes.

In fact, ... spoke about his opening at the Linux foundation, writing primarily about Kubernetes (and the Linux kernel).

That's something even more heavy-duty CLI focused than what I do. In such positions, if you can't manage via the CLI, you'd get no respect from devs (and deployers) -- and you're (best case) a couple of years away from helpful GUI tools.

(A couple of weeks ago, one of our QA asked me to illustrate the problems I was having with a new software feature. The only way I could do so was via the CLI. So there I was, typing in commands with multiple options, QA hovering over my shoulder, along with a REST call. Everyday work for me -- and I had done that often enough that I felt (only) a slightly hightened sense of tension.)

One of the other speakers (...) mentioned that they had a dev in their doc team who helped automate their work. To me, that's a rare luxury. We do our own tooling to build our docs. 

To answer ,,,'s Q, it's mostly Linux-focused bash, though we also need to work through PowerShell to illustrate our Azure/AD scripts.

(There are subtle differences between the bash on Macs, based on BSD, and bash on Linux, which we support in production, which can lead to interesting discussion with our devs, who mostly use Macs.) (edited)

mikejang [5:28 AM]
One other thought -- in principle, GUI tools are almost *never* (and I say that with a relatively confident certainty) as complete as corresponding tools at the CLI.

In the one case that I know of where the GUI was as complete as the CLI (Samba Web Administration Tool, aka SWAT), the UI was IMO awful. It doesn't surprise me that SWAT is no longer included in the default build of most Linux distros.

It's the reason why end users who are power users of our software (typically SysAdmins and DevOps specialists) use the CLI. (edited)

mikejang [5:37 AM]
Some of us had a post talk discussion with the director of the local university TW program, and we were brainstorming how her students might gain some of these skills.

**Comment by ericholscher** [comment]
Seems like a good thing to write up in the guide under a career section
