### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#465]
Just wanted to let you know that there are a few dead links on your style guide [http://www.writethedocs.org/guide/writing/style-guides/] page.

- [x] Pebble Road [https://www.pebbleroad.com/articles/Creating-Maintaining-a-Web-Style-Guide]
- [x] Pressly [http://blog.pressly.com/2013/09/24/5-style-guides-craft-content/]
- [x] IBM [https://www.redbooks.ibm.com/Redbooks.nsf/ibmpressisbn/9780132101301?Open]

**Comment by plaindocs** [comment]
@eirinikos another nice easy one :-D

**Comment by eirinikos** [comment]
thanks @plaindocs !! ❤️
