### ISSUE TITLE
Standardize schedule slugs / links / etc

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#480]
We've recently introduced a number of regressions because we hard code the talk title into the schedule. 

We should really just use the slug in the schedule yaml, and get the title from the source of truth, which is the speaker yaml.

And when we look at that we should also add a way to arbitrarily add a link to any other schedule entry, such as unconf and jobfair. 

FAO @ericholscher

**Comment by mxsasha** [comment]
Related to #674

**Comment by plaindocs** [comment]
Right. This year we tried to use Grorg as a source of truth, but that breaks down as soon as you have multiple speakers for a talk.

**Comment by mxsasha** [comment]
Wait, but we extract data from grorg into YAML, right? While building the website we don't pull data from grorg?
Having multiple speakers could be a feature we could add to grorg, but that would also mean having a fancy enough CFP form and things like that, so I'm not sure whether it's worth it if we can adjust the YAML for one or two edge cases.
(Also see https://trello.com/c/XqWI5rk3/218-grorg-improvements)
