### ISSUE TITLE
Meetups: List examples of successful Meetup Topics

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#488]
Idea: Collect successful meetup topics from various groups, and add them to the WtD Meetup organizer guide.

For Write the Docs PDX: 

* "Document Yourself"
* "UI Text"
* "Lightning talks: what are you looking for in a new writer"

If you're a meetup leader, or have seen successful WtD Meetups, add your reflections in the comments.

**Comment by KyleBlankRollins** [comment]
From WTD SLC:

- **Collaborating with stakeholders.** We had a local content strategist share her insights on aligning goals on projects.
- **Contributing to open source projects.** Getting started with Github and open source projects.
- **Creating content with limited resources and support.** A case study of how to approach tight deadlines and less-than-ideal situations.

**Comment by chihwaro** [comment]
I'll work on adding these.
