### ISSUE TITLE
Meetups: Set up generic letter asking for help

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#489]
Based on @meker12 's shared doc here: https://docs.google.com/document/d/1L49inF4ftTHqBYukOnu6seHThlFxqtTlllHQ6mwqel0/mobilebasic

**Comment by uwikaiddi** [comment]
I'll be working on this document for Writing Day

**Comment by uwikaiddi** [comment]
PR submitted

**Comment by mjang** [comment]
PR for the letter: https://github.com/writethedocs/www/pull/536
Second PR to link to the Meetup FAQ: https://github.com/writethedocs/www/pull/593/files
