### ISSUE TITLE
Mobile and Desktop Menus

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#492]
@ericholscher @xpostudio4   we're maintaining two menus, with as far as I can tell exactly the same content.  

We can probably just alter the top class, and include the list items so we're only maintaining one, right?

Or if not, we should have a plan about how we want the menus to differ.

**Comment by plaindocs** [comment]
I feel that we should be able to solve this either by using a macro or by passing variables from one to the other.

**Comment by mxsasha** [comment]
Let's look at it in #1010 which already included reviewing menus.

**Comment by mxsasha** [comment]
Closing as wontfix:
* [Moving menu content into YAML is complex and barely helpful](https://github.com/writethedocs/www/pull/1114#issuecomment-539491968)
* The structure is way too different to make both menus a single HTML file.
