### ISSUE TITLE
Photos in the footer stretched 

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#509]
@ericholscher adding the OpenHelp logo to the footer in http://www.writethedocs.org/conf/cincinnati/2018/sprints/ deforms the photos.

**Comment by ericholscher** [comment]
Can you attach an image? I don't see it.

**Comment by plaindocs** [comment]
![screenshot from 2018-04-27 10-01-16](https://user-images.githubusercontent.com/95874/39375086-f35572be-4a01-11e8-8d79-2030f4ca288c.png)

Is what I see (FF on Linux)

**Comment by plaindocs** [comment]
I think we fixed this?
