### ISSUE TITLE
Merging the Lone Writer's Guide with Write The Docs Website

### ISSUE THREAD

**Issue by cwcromwell** [writethedocs/www#511]
Write The Docs San Francisco Bay Area is working on a Lone Writer's Guide at our GitHub, which we'd like to offer as an addition the the Write The Docs website some time in the future.

I thought it would be good to make sure that someone on your end knows what we're up to. 

Before submitting a pull request we would do the following:
- Remove anything that duplicates what is on the WTD site, or submit it separately if it is an improvement
- Organize the guide into a document that can be easily linked to the WTD site
- Fill in areas where material is weak or incomplete, so that it will be a useful guide on day one of appearing on the site.

I'll be in Portland, including the Writing Day event, if anyone working on your site is available to chat about that. It would be great to have any feedback about how to submit the PR.

Here's a link to the GitHub repo: 
(https://github.com/San-Francisco-Write-The-Docs/lone-writers-guide)

**Comment by plaindocs** [comment]
Hey @cwcromwell

That sounds good to me. Happy to be the point of contact for this, and look forward to chatting on writing day.

**Comment by cwcromwell** [comment]
Fantastic. See you then.

**Comment by plaindocs** [comment]
Hey @cwcromwell Shall we close this? What state is stuff on your side at?

**Comment by mxsasha** [comment]
Closing this, please reopen if you're still interested in working on this.
