### ISSUE TITLE
YAMLize sponsors so we don't have to write lists 

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#516]

**Comment by ericholscher** [comment]
👍

**Comment by plaindocs** [comment]
Seems like we should get on this before getting too many sponsors :-D I'll see what I can do.

**Comment by plaindocs** [comment]
Hey @ericholscher are we at all worried about maintaining the timeline of sponsors in old blog posts here? 

Like, if we have three starting sponsors and publish a post, and then update the YAML with more sponsors, are we ok to just have it show all of them? 

My gut feeling is that is fine.

**Comment by ericholscher** [comment]
This was mainly for the website, not for blog posts. But it's probably fine either way.

**Comment by plaindocs** [comment]
Yeah, I mean conf news blog posts where we list them by hand.
