### ISSUE TITLE
Validate config yaml

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#528]
We need to validate `_data/config*` with https://github.com/23andMe/Yamale (there may be *minor* diferences between those files, and there shouldn't be.

Mostly just required keys, and whether they are int / bool / text for now.

**Comment by plaindocs** [comment]
https://github.com/23andMe/Yamale#schema

**Comment by Reezaali** [comment]
#551 starts to address this issue. This PR has the schema file, and a fix to the Prague data file. When you run Yamale, it validates the Prague data file. 

ToDo: Standardize the data fields, order, data types of the other data files.
