### ISSUE TITLE
Gap in Producing documentation inside a Support team

### ISSUE THREAD

**Issue by alexgii90** [writethedocs/www#539]
My Suggestions for this section:

http://www.writethedocs.org/guide/writing/support-team/

To put it in context, I am a Technical Writer that works as part of the Support team, but I never answer tickets or calls (in fact I never have direct contact with customers at all). What I do is interact closely with the team and have them assign me tasks based on problems they have encountered with customers.
I think this is an important distinction, because the site focused mainly on Support people who also write, or writers who also Support people. While both are important, I feel like the third (me) who are Writers who work with Support people, but maintain their own individual role. 

I am attaching my suggested text for this section. 
[Write the Docs 2018 Submission - Working with Support.docx](https://github.com/writethedocs/www/files/1977947/Write.the.Docs.2018.Submission.-.Working.with.Support.docx)

**Comment by plaindocs** [comment]
This is an easy fix, paste in an RST format.

**Comment by plaindocs** [comment]
Thanks for contributing this material @alexgii90 !
