### ISSUE TITLE
Add roundup blog posts to "Thanks" section of the site

### ISSUE THREAD

**Issue by ericholscher** [writethedocs/www#56]
If anyone is looking for a way to contribute back to WTD — it would be great to find links to all the round up blog posts and add them to the main conf website under the "Thanks" section. You can find the page to edit here: https://github.com/writethedocs/www/blob/master/docs/conf/na/2016/index.rst

It should just be a link to the blog posts under a heading like "Write ups from the community".

The `#writethedocs` hashtag on Twitter is probably the best place to find write ups, as well as Google for "write the docs 2016" or similar.

* [x] NA 2017
* [x] NA 2016

* [x] EU 2017
* [x] EU 2016

Probably not worth the effort:

* [ ] NA 2015
* [ ] EU 2015

**Comment by plaindocs** [comment]
Did you make a PR for that?

**Comment by nikblanchet** [comment]
… Yes and you approved it.

**Comment by plaindocs** [comment]
But did you see all the other years?

**Comment by plaindocs** [comment]
Let's not both with 2015.
