### ISSUE TITLE
Create a WTD linter

### ISSUE THREAD

**Issue by ericholscher** [writethedocs/www#58]
A few people in Slack were talking about having a set of custom rules that we would implement in a linter. This ticket tracks ideas that we think might be cool for a WTD linter:
- Gendered pronouns (he/she/his/her)
- Semicolons

Feel free to comment below with more suggestions!

**Comment by ericholscher** [comment]
Some great data here: https://github.com/wooorm/retext-equality/blob/master/script/gender.yml

**Comment by wooorm** [comment]
@ericholscher Awesome! Here’s a little pitch :)

So, `retext-equality` is part of [alex](https://github.com/wooorm/alex).

Both Mapbox and Shopify have built there own tools based on `retext-equality` (and some other tools I made), which look a bit like alex: [`Rorybot`](https://github.com/Shopify/rorybot), from Shopify, and [`retext-mapbox-standard`](https://github.com/mapbox/retext-mapbox-standard), from Mapbox.

In essence, they’re often using [remark](https://github.com/wooorm/remark) (to read markdown in), then skipping the syntax and extracting just natural language, which is processed by [retext](https://github.com/wooorm/retext), and then some plug-ins inspect the natural language syntax tree and warn about certain constructs.

</end-pitch>

I’d love to help out if there’s interest in implementing something with these tools, feel free to ask any Q if so!

**Comment by ericholscher** [comment]
Sounds great. I think it probably makes the most sense to start by documenting these efforts (as you've nicely done here :) -- and then if we find a place where we can contribute (perhaps by building a tool that works across markup languages), then we can build out some actual code.

**Comment by plaindocs** [comment]
Hi @wooorm ! Awesome to have your input on this! 

A couple of questions from when I looked at it briefly a few weeks back:
- it seems more of a library than a straight tool + config setup
- seems to check within fenced and inline code by default, is this easy to toggle?
- looks like markdown only, what is the scope for checking ReST and Asciidoctor as well?

**Comment by wooorm** [comment]
Hi @plaindocs!
1. Sort of, but then replace “library” with “lots of modules / plugins / utilities”!
2. What? Could you explain what your thinking in more detail?
3. remark is for markdown, retext is for natural language.  Other markup syntaxes would also work with retext but with less sophistication. If retext is combined with remark, it’s possible to ignore certain syntax construct.

Does that answer your questions?

**Comment by plaindocs** [comment]
Hi @wooorm,
1. Sure! 
2. OK. So I looked at `mapbox-retext` first, and followed that to the original `retext` - and I think one of the reasons they forked, rather than just used a config file is that remark seems to process codeblocks on markdown, when it probably should not. 
3. Makes sense.

So my vision (which is _only that_) is that a text linter for WTD should be a "single install" (whatever that means, ie, you can install, with plugins, but don't have to write code to use), with a config file. Ideally you be able to parse markdown (variants?), restructured text and asciidoctor, and the config file would specify what checks you're making. 

And along those lines, https://github.com/textlint/textlint looks closer to my thoughts than `retext`.

**Comment by wooorm** [comment]
It’s not really the case that someone “forked” though; `retext-mapbox-standard` is an example of how retext and remark can be used! Mapbox / Shopify wanted exactly what you described in your “my vision” paragraph. Put in other words, think of these two projects as example node servers built with express, but then express is retext/remark, and the servers are retext-mapbox-standard / rorybot.

> remark seems to process codeblocks on markdown, when it probably should not.

No, it doesn’t, or at least it shouldn’t, what gives you that idea?

> And along those lines, https://github.com/textlint/textlint looks closer to my thoughts than retext.

It’s pretty cool! `textlint-plugin-markdown` uses `remark` under the hood to parse markdown, so of course it’s good. 😉  retext does make it a bit easier to check sentences / words / symbols / punctuation in plug-ins though

**Comment by plaindocs** [comment]
Flagging #68 for future ref. @wooorm I'll get back to you on this shortly.

**Comment by brainwane** [comment]
I was looking around for linters before Frances Hocutt and I made https://github.com/OpenNewsLabs/open-project-linter/ and wish I had come across this thread! Am interested in what you decide to use or make.

**Comment by plaindocs** [comment]
Hi @brainwane 

We recently added some basic checks using [Vale](https://github.com/ValeLint/vale) -> check the code in .vale on the master branch, or the PR linked above.

I'm also just this very moment adding some stuff in https://github.com/writethedocs/www/pull/171

More thoughts and suggestions always welcome.

**Comment by plaindocs** [comment]
Hi @brainwane 

We recently added some basic checks using [Vale](https://github.com/ValeLint/vale) -> check the code in .vale on the master branch, or the PR linked above.

I'm also just this very moment adding some stuff in https://github.com/writethedocs/www/pull/171

More thoughts and suggestions always welcome.

**Comment by plaindocs** [comment]
And if anyone has an easy to implement way of validating the contents of code blocks in markdown and / or rst I'm **all ears**.

**Comment by ericholscher** [comment]
@plaindocs I should be able to write a pretty simple sphinx extension to do it, if one doesn't already exist. Make a new ticket for it?

**Comment by ericholscher** [comment]
https://github.com/myint/rstcheck looks promising.
