### ISSUE TITLE
Suggested site architecture

### ISSUE THREAD

**Issue by cwcromwell** [writethedocs/www#590]
I hear there's a plan to redesign and rebuild the WTD.org website. I wanted to suggest a new architecture for the site. I think this will make the site easier to use and more effective. 

TYPES OF CONTENT: HOW I ARRIVED AT THE TABLE OF CONTENTS THAT I'M SUGGESTING BELOW

The most desirable and important learning content on the WTD site falls into three categories. 

1.) Company culture. Sometimes you realize that you need to influence the organization you work for, in order to help it be better at documentation. 

2.) Docs for the first time. There was a significant group at WTD Portland comprising engineers who have never created docs and would like to learn to do it well — but don’t know where to start. I chatted with one engineer who said he wasn’t sure what kind of document to produce or how to go about outlining and writing it. 

3.) Producing better documentation. Some people are seeking only information about practices that will lead to the best documentation. They want to know about advanced techniques to de-complicate tasks for the end user and save them time, effort and money. 

It will be better for users of the site if information about all these areas is available and easy to find, but they can pick just one or use them one at a time. 

Also the site should be organized as simply as possible, so that it’s easy to find what you’re looking for. I think it would be great if the full site could be available on the left-hand sidebar from every page. 

SECTIONS OF THE WEBSITE

This is one possible way to organize the site.

The five topics marked with a pound sign (#)  at the right represent material that apparently doesn’t exist now.

1.) The community

* About us
   - What is a documentarian?
   - Origin story
   - About the WTD org
   - Team
* Conferences
   - List of existing conferences and one-day events
   - How to start a conference or one-day event where you are
* Meetups
   - list of existing meet ups
   - organizers guide
* Slack
   -how to join
* Newsletters and mailing lists
* Job board

2.) Online Guides

* Documentation for beginners
   - How to get started
   - Design patterns for docs #

* Documentation Guide
   - Defining excellent documentation
   - Documenting APIs

* Building a documentation culture at your company
   - Why
   - How 
 
* Guide to tools and processes (tools you use are a different subject from what you make.)
   - Guide to static site generators
   - Roundup of other miscellaneous tools (editors, CMS’s, publishing tools)
   - Docs as code
    - Better documentation practices #
      + Analytics #
      + Usabilty testing #

 3.) Archived Learning Resources

* Videos (of Conferences, meetups, etc.) 
* Podcasts
* Links (to excellent documentation; to other learning resources) #

**Comment by ericholscher** [comment]
Sounds like this is mostly just a request to restructure the guide. For example, why would the guide be separate from the other sections of "online guides"? Seems like beginners, culture, and tools would be fine living inside our current guide.

**Comment by cwcromwell** [comment]
I have to concede they don't need to be separate guides. They could be in one guide as separate sections and accomplish the same thing suggested in the PR.

I do think it would help to organize the material into the main topic areas that people look for. It is easier to find the parts you need if the site is more strictly organized; some users might be new to documentation, but not have any issues with company culture; and vice versa. 

A focused section about each topic might also lead to better content, because it will be evident if something is missing.

**Comment by mxsasha** [comment]
We should consider this in the context of #527, closing this issue so we can have the discussion in one place.
