### ISSUE TITLE
Update Speaking Tips

### ISSUE THREAD

**Issue by plaindocs** [writethedocs/www#658]
To make projector ratio conditional on Prague / Portland / Etc

FAO @kelly-o

**Comment by plaindocs** [comment]
Hey @ericholscher - do you know off the top of you your head what we need to tweak to be able to template conditionalise inside included rst files?

**Comment by ericholscher** [comment]
@plaindocs not 100% following. An example would be useful.

**Comment by plaindocs** [comment]
So speaker tips are mostly the same for all confs, so we have that info in `include` and then include it from each conf.

But if you conditionalise stuff in include, it doesnt work, because of where we processes the templating.

Make sense?

**Comment by plaindocs** [comment]
Fixable by #738

**Comment by plaindocs** [comment]
Prague 4:3
Portland 16:9

**Comment by plaindocs** [comment]
Prague needs updating for 4:3 on the site, and #1010 should take this into account.

**Comment by plaindocs** [comment]
Prague is now 

Resolution: WUXGA, 1920 x 1200

Aspect ratio: 16:10

Interfaces: USB 2.0 Type A, USB 2.0 Type B (Service Only), RS-232C, Ethernet interface (100 Base-TX / 10 Base-T), Wireless LAN IEEE 802.11a/b/g/n (optional), VGA in, VGA out, DVI in, BNC in, HDBaseT, Stereo mini jack audio out, Stereo mini jack audio in (3x), HDMI (HDCP 2.2)
