### ISSUE TITLE
List of resources from Slack

### ISSUE THREAD

**Issue by ericholscher** [writethedocs/www#677]
From `rdmitchelljr`

I ran an unconference where I asked people what resources they use to create content. This is the list:
Documentarian Resources
Websites with examples of good documentation
•    Stripe - https://stripe.com/docs -Great for API
•    Google Material Design - https://material.io/design/ - Good examples of different layouts
•    IBM Knowledge Center - https://www.ibm.com/support/knowledgecenter/en/ - solid examples of code that isn’t necessarily API.
Style Guides
•    Biosystems Engineering Technical Guide - https://msu.edu/course/be/485/bewritingguideV2.0.pdf (contains a list of action verbs and a table of wordy         text vs concise text)
•    Microsoft - https://docs.microsoft.com/en-us/style-guide/welcome/
•    Apple - https://help.apple.com/applestyleguide/
•    Salesforce - https://developer.salesforce.com/docs/atlas.en-us.salesforce_pubs_style_guide.meta/salesforce_pubs_style_guide/overview.htm
Documentation Guides
•    Dozuki Guide to Technical Writing - https://www.dozuki.com/tech_writing/
•    Hitchhiker’s Guide to Documentation - https://docs-guide.readthedocs.io/en/latest/
•    Wikiversity Technical Writing - https://en.wikiversity.org/wiki/Technical_writing
•    Write the Docs - http://www.writethedocs.org/guide/
Dictionaries
•    Miriam-Webster - https://www.merriam-webster.com/
•    https://www.dictionary.com / https://www.thesaurus.com / https://www.vocabulary.com
•    Linguee - https://www.linguee.com/ (phrases/idioms)
•    Lexique Pro - http://www.lexiquepro.com/  (offline dictionary/term list builder…old)
Grammar/Complexity
•    Center for plain language - https://centerforplainlanguage.org/
•    Simple English Checker - https://www.online-utility.org/english/simple_basic_helper.jsp
•    Acrolinx - https://www.acrolinx.com/
•    Hemingway Editor - http://www.hemingwayapp.com/
•    Grammarly - https://www.grammarly.com/
SEO Analyzer
•    Headline Analyzer - https://coschedule.com/headline-analyzer
Translation Tools
•    https://translate.google.com
•    https://www.deepl.com/translator
•    X-bench - https://www.xbench.net/
Ideas
•    Courses in Communication (agreed upon that effective communication skills is key)
•    Use Knowledge Owl to manage content
•    Latest news and trends - https://www.Idratherbewriting.com
•    Podcasts:
               https://wordsworkpodcast.com/2018/01/22/e07-catherine-minden-revamping-the-microsoft-writing-style-guide/
               http://podcast.writethedocs.org/ (edited)

**Comment by djwfyi** [comment]
Should this go under Guide/Tools of the Trade or as a new Examples & Tools page under Learning Resources?

**Comment by plaindocs** [comment]
Looking a little closer it seems like a mix:

- SEO, Dictionaries are tools
- Guides, do we have a section for other doc guides?
- What about examples of good docs? 

What do you think?

**Comment by djwfyi** [comment]
Some additional links from Slack to also add to avoid both bias and ableism:

• https://www.linguisticsociety.org/resource/guidelines-inclusive-language
• https://developers.google.com/style/inclusive-documentation
• https://consciousstyleguide.com/
• https://docs.microsoft.com/en-us/style-guide/bias-free-communication
• https://www.linguisticsociety.org/content/further-content-related-inclusive-language-guidelines
• https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/accessibility-terms

**Comment by plaindocs** [comment]
This *poor* issue.

**Comment by djwfyi** [comment]
I want to work on it, but I'm too busy figuring out asciidoc to also take on rST right now. Eventually.

**Comment by plaindocs** [comment]
Hey @dwhitelf that was  in no way aimed at you! :-) Just at me noticing how it has been open.

On the other hand, if you'd like to write the updates in Asciidoc I'll happily convert them to RST using pandoc for you.
