### ISSUE TITLE
Missing info on Sphinx/ReST in Documentation Guide

### ISSUE THREAD

**Issue by boltzmann-brain** [writethedocs/www#695]
I'm planning to contribute to the reStructured Text sections, which have placeholders under Markup Languages but no content yet.

I might also add stuff about text editors for ReST, and Sphinx's unorthodox way of making TOCs (the latter as an addition in the Introduction to Sphinx topic).

**Comment by plaindocs** [comment]
Sounds great. :-)

**Comment by plaindocs** [comment]
Closing this for now, please reopen if you'd like to contribute.
