### ISSUE TITLE
Why Write The Docs

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#70]
I think we need a separate page for the "Write The Docs Worldview"

Is it a "Worldview", a "Philosophy", or a "Why Write The Docs"?

Well, here's a first draft, h/t @meker12 

"We consider everyone who cares about communication, documentation, and their users to be a member of our community. This can be programmers, tech writers, customer support reps, marketers, and anyone else who wants people to have great experiences with software.

Our meetups and conferences create a time and a place for the global community of Documentarians to share information, discuss ideas, and work together to improve the art and science of documentation. (From http://www.writethedo...­) Focus of talks will vary from meetup to meetup, but the opportunity to see and learn about documentation from different perspectives is one of goals. And the goal for all of us is to create great content for the intended audience and purpose,"

**Comment by mjang** [comment]
A separate page for a "Worldview" would help us speak from the same page, when explaining the "Philosophy" of "Why Write The Docs" to documentarians who haven't yet heard of us.

**Comment by ericholscher** [comment]
+1 -- I've been scheming this for a while now, but haven't been able to properly give it words. Perhaps I should just transcribe the intro from the conference, for now :)

**Comment by mjang** [comment]
Close with https://github.com/writethedocs/www/pull/67
