### ISSUE TITLE
Set up template Code(s) of Conduct (CoC) for conferences and meetups

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#71]
The current WTD CoC for conferences: http://www.writethedocs.org/code-of-conduct/

The current WTD PDX CoC for Meetups: https://www.meetup.com/Write-The-Docs-PDX/pages/19618086/Code_of_Conduct/

I believe both are acceptable, but, others may disagree. I note that the WTD PDX CoC has not been reviewed by anyone with legal training (as least not to my knowledge)

 If both are acceptable, I suggest that we present the WTD PDX CoC as a template for other WTD Meetups.

**Comment by mjang** [comment]
Assuming we accept the new CoC, I'll limit this issue to the template for Meetups (which I think can be a "short form" version) of our global CoC.

**Comment by AWS-SF** [comment]
Based on our dicussion, I'll go ahead and try drafting a "short-form" that meetup users can drop into introductory slide decks, web pages, etc..

**Comment by mjang** [comment]
@ericholscher My intent -- you'd review this before it was merged. cc @rosewms I know you have an alternative.

**Comment by mjang** [comment]
Short form CoC PR merged: https://github.com/writethedocs/www/pull/531

Separate PR to link to the Minimal Viable Meetup checklist

**Comment by mjang** [comment]
Closing as the linking PR is now merged ( https://github.com/writethedocs/www/pull/595 )
