### ISSUE TITLE
Non-fatal Error in build

### ISSUE THREAD

**Issue by mjang** [writethedocs/www#777]
"/home/mike/Documents/GitRepo/www/docs/about/learning-resources.rst:5: WARNING: toctree contains reference to nonexisting document 'videos'"

I'm guessing there's a broken link

**Comment by plaindocs** [comment]
Hi Mike,

I totally missed this! Thanks! 

Fixed in 0eb98045923

**Comment by plaindocs** [comment]
Also, notice the commit message :-(.
