### ISSUE TITLE
Add more information about making meetups sustainable

### ISSUE THREAD

**Issue by ericholscher** [writethedocs/www#80]
We need to help meetup organizers build a sustainable meetup that is ongoing. I [asked](https://twitter.com/ericholscher/status/773275151886524416) on Twitter about this and got a few answers, which might also prove interesting for taking some content from:
- https://www.elastic.co/community/usergroupguide
- http://stumptownsyndicate.org/wiki/User_group_setup_checklist

I think to start:
- Recommending at most 10 meetups a year (skip August & Dec, as most people are on vacation/checked out)
- Recommend having at least 2 people who can organize the meetup

**Comment by plaindocs** [comment]
@thatdocslady wanna incorporate some of this into the meeting FAQ? Or shall I have a bash?

CC @mjang

**Comment by mjang** [comment]
The ELK and Stumptown lists are great, but feel a bit overwhelming. So if we use the content, we should take care to "keep it simple" -- maybe split it into 

1) Minimal viable meetup checklist (e.g. Meeting space)
2) Nice to haves (e.g. Twitter account)

**Comment by mjang** [comment]
One more "nice to have" recommendation (not shown in either of Eric's links):

* Include at least two regular sponsors
(with 1 sponsor, the meetup seems to belong to them. with >=2 sponsors, the meetup belongs to the community)

**Comment by plaindocs** [comment]
I'm with Mike on the lists, shorter is better.

I also like the sponsorship idea, BUT if the only thing being sponsored is venue how does that work?

**Comment by mjang** [comment]
In PDX, we have two main sponsors -- basically 1 for venue, 1 for meetup food. I know with (some) other meetups, they rotate locations (different companies, ergo multiple sponsors).

**Comment by plaindocs** [comment]
Does that still work if the venue sponsorships are on company premises? No reason why it shouldn't.

I definitely like it as something to aim for.

**Comment by ericholscher** [comment]
:+1: to not full sale including the above lists, but I'd like a "sustainability" section in our meetup docs somewhere, and for it to address the issues mentioned :)

**Comment by thatdocslady** [comment]
On it :) looks like great info for the FAQ

**Comment by mjang** [comment]
I think we've addressed the content of this issue, and can close it.

**Comment by mjang** [comment]
If someone wants to add more info on making meetups more sustainable, great! You're welcome to reopen this issue.
